[package]
name = "serde-dig"
version = "0.1.0"
authors = ["Benjamin Trent <4357155+benwtrent@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"